---

- name: fetch helm from repository
  become: yes
  ansible.builtin.uri:
          url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          dest: /home/ubuntu/get_helm.sh

- name: alter file permissions
  become: yes
  ansible.builtin.file:
          path: /home/ubuntu/get_helm.sh
          mode: 0700

- name: run downloaded file
  become: yes
  ansible.builtin.shell:
          cmd: '/home/ubuntu/get_helm.sh'
