---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: samplefrontend-deployment
        namespace: default
spec:
        replicas: 3
        selector:
          matchLabels:
            app: samplefrontend
        strategy:
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: samplefrontend
          spec:
            containers:
              - name: frontend
                image: samplefrontend:1.0
                imagePullPolicy: Never
                ports:
                        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
        name: frontend-exposure
        namespace: default
spec:
  selector:
    app: samplefrontend
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
      nodePort: 30001

