---

- name: install python stuff
  become: yes
  ansible.builtin.apt:
          name: ['python3-dev', 'python3-setuptools', 'python3-pip']
          state: latest
          update_cache: yes

- name: update pip
  ansible.builtin.pip:
          name: ['pip', 'openstacksdk']
          state: latest

- name: install pexpect
  become: yes
  ansible.builtin.pip:
          name: pexpect

- name: install kubernetes library
  become: yes
  ansible.builtin.pip:
          name: kubernetes

