---

- name: set context
  ansible.builtin.shell:
          cmd: 'kubectl config set-context --current --namespace rook-ceph'

- name: create ceph cluster
  ansible.builtin.shell:
          cmd: 'kubectl create -f /home/ubuntu/rook/deploy/examples/cluster.yaml'
