#COMMON
availability_zone: melbourne-qh2-uom
instance_flavor: uom.mse.2c9g
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999

#VOLUMES
volumes:
        - vol_name: personal_vol
          vol_size: 50

#SECURITY GROUPS
security_groups:
        - name: ssh_msl
          description: Allows SSH (port 22) from world
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: 0.0.0.0/0  

#INSTANCES
mrc:
        - name: personal_demo
          volumes: ['personal_vol']
          keypair: mistletoe_private
