---

- name: copy backend folder to cluster
  ansible.builtin.copy:
          remote_src: no
          force: yes
          src: /home/mesl/playbooks/cluster_finalback/backend
          dest: /home/ubuntu

- name: build images
  become: yes
  ansible.builtin.shell:
          cmd: 'docker build -t backend:1.0 /home/ubuntu/backend'
