
- name: create views
  hosts: control
  vars:
          ansible_ssh_private_key_file: ~/mesl.pem
  tasks:
    - name: copy create view file
      copy:
        src: /Users/belkok/Documents/GitHub/COMP90024/COMP90024_A2/Ansible/couchdb_createviews/createviews/create_views.sh
        dest: /home/ubuntu

    - name: create views
      command: sh /home/ubuntu/create_views.sh

