---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: webapp-backend
        namespace: default
spec:
        replicas: 3
        selector:
          matchLabels:
            app: finalbackend
        strategy:
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: finalbackend
          spec:
            containers:
              - name: backend
                image: backend:1.0
                imagePullPolicy: Never
                ports:
                        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
        name: webapp-backend-svc
        namespace: default
spec:
  selector:
    app: finalbackend
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
      nodePort: 30003

