---

- name: building images
  hosts: meslworkers
  vars:
          ansible_ssh_private_key_file: /home/mesl/.ssh/mesl.pem
  roles:
          - role: images

- name: building images with different host
  hosts: couchdb
  vars:
         ansible_ssh_private_key_file: /home/mesl/.ssh/cloud.key
  roles:
          - role: images
