- name: setup on nodes with mesl.pem private key
  hosts: mesl
  vars_files:
          - inventory/vars.yaml
  vars:
          ansible_ssh_private_key_file: /home/mesl/.ssh/mesl.pem

  roles:
    - role: python
    - role: docker
    - role: k8s

- name: setup on node with cloud.key private key
  hosts: couchdb
  vars_files:
          - inventory/vars.yaml
  vars:
          ansible_ssh_private_key_file: /home/mesl/.ssh/cloud.key

  roles:
    - role: python
    - role: docker
    - role: k8s
