---

- name: install python stuff
  become: yes
  ansible.builtin.apt:
          name: ['python3-dev', 'python3-setuptools', 'python3-pip']
          state: latest
          update_cache: yes

- name: update pip
  ansible.builtin.pip:
          name: ['pip', 'openstacksdk']
          state: latest

- name: install packages for using repository
  become: yes
  ansible.builtin.apt:
          force_apt_get: yes
          update_cache: yes
          name: ['apt-transport-https', 'ca-certificates', 'curl']

- name: Download Google Cloud public signing key
  become: yes
  ansible.builtin.uri:
          url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
          dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes apt repository
  become: yes
  ansible.builtin.shell:
          cmd: 'echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list'

- name: Install kubelet, kubeadm, kubectl
  become: yes
  ansible.builtin.apt:
          force_apt_get: yes
          update_cache: yes
          name: ['kubelet', 'kubeadm', 'kubectl']

- name: Configure kubernetes applications
  become: yes
  ansible.builtin.shell:
          cmd: 'apt-mark hold kubelet kubeadm kubectl'
