# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: mesl
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: test_worker_vol
    vol_size: 100

# Security group
security_groups:
  - name: ssh
  - name: default

# Instance
instances:
  - name: test_worker_node
    volumes: ['test_worker_vol']


