---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: couchdballocate-deployment
spec:
        replicas: 1
        selector:
          matchLabels:
            app: couchdballocate
        strategy:
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: couchdballocate
          spec:
            containers:
              - name: couchdballocate
                image: couchdballocate:1.0
                imagePullPolicy: Never

